### ISSUE TITLE
Having no solution file results in setting file being created in project folder

### ISSUE THREAD

**Issue by mseskas** [tevux-tech/tevux-tools-repositorysettings#2]
If you have project without solution file on project rebuild operation settings files are created in project folder. This is not an issue just checking if this was intentionally.
![image](https://user-images.githubusercontent.com/5638254/212002532-bace95d6-1157-44d3-bd4e-e32dddbf84ad.png)

**Comment by mseskas** [comment]
It happend again. This time with solution file. It is Skoll, .Net Framework 4.6 WPF app.
![image](https://user-images.githubusercontent.com/5638254/213137439-57df842c-4bff-4eca-92d5-d65e80f858a5.png)

**Comment by devbotas** [comment]
@mseskas 

1. Yes, if there no solution, files are added to the project folder.
2. Apparently, .NET 4.x.x apps behave slightly differently. I think this is related to Nugets, as they do not add Content file directly to the project in the .NET Core projects (remember ...-Source nugets that stopped working?), and .gitignore. .editorconfig and other files are actually content files. So, in .NET Framework projects they are added once you install the nuget, and then also when you build the project. In .NET Core projects, files are only added when you build the project. So, it is what it is and I can't do much here, and maybe there's no point. In .NET Framework, you just delete those files in project folder and carry on.
